<?php
session_start();
include 'includes/db.php';
$pageTitle='Partner With Us | Join CleanNora as a Service Professional';
$pageDescription='Login and apply to become a CleanNora service partner. Submit your profile and KYC documents for partner onboarding.';
$success=false;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['partner_apply'])){
$name=trim($_POST['name']??'');$phone=preg_replace('/\D+/','',$_POST['phone']??'');$email=trim($_POST['email']??'');$city=trim($_POST['city']??'');$area=trim($_POST['area']??'');$service=trim($_POST['service']??'');$experience=trim($_POST['experience']??'');
if($name===''||strlen($phone)<10||$city===''||$service===''){$error='Please complete all required fields.';}
else{
mysqli_query($conn,"CREATE TABLE IF NOT EXISTS partner_applications (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,phone VARCHAR(20) NOT NULL,email VARCHAR(160) NULL,city VARCHAR(100) NOT NULL,area VARCHAR(160) NULL,service VARCHAR(100) NOT NULL,experience VARCHAR(80) NULL,aadhaar_ref VARCHAR(255) NULL,pan_ref VARCHAR(255) NULL,photo_ref VARCHAR(255) NULL,status VARCHAR(30) DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$stmt=mysqli_prepare($conn,"INSERT INTO partner_applications(name,phone,email,city,area,service,experience,status) VALUES(?,?,?,?,?,?,?,'new')");
if($stmt){mysqli_stmt_bind_param($stmt,'sssssss',$name,$phone,$email,$city,$area,$service,$experience);$success=mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);}if(!$success&&!$error)$error='Application could not be submitted. Please call +91 92050 80012.';
}}
include 'includes/header.php';?>
<style>.pw-hero{background:linear-gradient(135deg,#063a29,#0a5039);color:#fff;padding:58px 20px}.pw-wrap{max-width:850px;margin:auto}.pw-hero h1{font-size:clamp(34px,5vw,55px);font-weight:850}.pw-hero span{color:#f4bf19}.pw-card{margin:38px auto;background:#fff;border:1px solid #e0e9e5;border-radius:22px;padding:28px;box-shadow:0 12px 35px rgba(6,58,41,.08)}.pw-login{max-width:520px}.pw-card label{display:block;font-weight:750;margin:13px 0 6px}.pw-card input,.pw-card select{width:100%;padding:13px;border:1px solid #ccd9d3;border-radius:10px}.pw-btn{width:100%;border:0;border-radius:12px;background:#f4bf19;color:#17372d;font-weight:850;padding:14px;margin-top:18px}.pw-docs{background:#f6f9f7;padding:20px;border-radius:16px;margin-top:22px}.pw-note{font-size:13px;color:#66736e}.pw-ok{text-align:center;padding:45px 20px}.pw-ok i{font-size:55px;color:#0b7048}.pw-ok h2{color:#063a29;font-weight:850}.pw-err{background:#fff0f0;color:#8c2020;padding:13px;border-radius:10px}</style>
<main><section class="pw-hero"><div class="pw-wrap"><h1>Partner <span>With Us</span></h1><p>Join CleanNora as a service professional. Login with your mobile number, complete your profile and submit KYC documents for review.</p></div></section><div class="pw-wrap">
<?php if($success):?><section class="pw-card pw-ok"><i class="bi bi-check-circle-fill"></i><h2>Thank You!</h2><p>Your partner application has been submitted successfully.</p><p><strong>Our team will contact you shortly.</strong></p><a href="/" class="btn btn-success mt-3">Back to Home</a></section>
<?php else:?><section class="pw-card pw-login" id="partnerLogin"><h2>Partner Login</h2><p>Verify your mobile number to continue.</p><label>Mobile Number</label><input id="pwPhone" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number"><div id="pwRecaptcha"></div><button type="button" class="pw-btn" id="pwSendOtp">Send OTP</button><div id="pwOtpBox" style="display:none"><label>Enter OTP</label><input id="pwOtp" inputmode="numeric" maxlength="6"><button type="button" class="pw-btn" id="pwVerifyOtp">Verify & Continue</button></div><p id="pwLoginMsg" class="pw-note"></p></section>
<form method="post" enctype="multipart/form-data" class="pw-card" id="partnerForm" style="display:none"><?php if($error):?><div class="pw-err"><?=htmlspecialchars($error)?></div><?php endif;?>
<h2>Partner Application</h2><input type="hidden" name="phone" id="pwVerifiedPhone"><label>Full Name *</label><input name="name" required maxlength="120"><label>Email</label><input type="email" name="email" maxlength="160"><label>City *</label><select name="city" required><option value="">Select area</option><option>Noida</option><option>Greater Noida</option><option>Greater Noida West / Gaur City</option><option>Indirapuram</option><option>Ghaziabad</option></select><label>Sector / Locality</label><input name="area" maxlength="160"><label>Service *</label><select name="service" required><option value="">Select service</option><option>Instant Maid</option><option>Cook</option><option>Beautician</option><option>Electrician</option><option>Plumber</option><option>Home Cleaning</option><option>AC Service & Repair</option><option>Other Home Service</option></select><label>Experience</label><select name="experience"><option>Fresher</option><option>Less than 1 year</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select>
<div class="pw-docs"><h3>Submit Documents</h3><p class="pw-note">Upload clear documents for verification. Aadhaar/PAN details should be handled securely and should not be exposed publicly.</p><label>Profile Photo</label><input type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp"><label>Aadhaar Document</label><input type="file" name="aadhaar_document" accept="image/jpeg,image/png,image/webp,application/pdf"><label>PAN Document</label><input type="file" name="pan_document" accept="image/jpeg,image/png,image/webp,application/pdf"></div>
<button class="pw-btn" type="submit" name="partner_apply">Submit Application</button><p class="pw-note" style="text-align:center">Need help? <a href="tel:+919205080012">+91 92050 80012</a></p></form><?php endif;?></div></main>
<script type="module">
import{RecaptchaVerifier,signInWithPhoneNumber}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
let confirmation=null;const msg=document.getElementById('pwLoginMsg');
document.getElementById('pwSendOtp')?.addEventListener('click',async()=>{try{const n=document.getElementById('pwPhone').value.replace(/\D/g,'');if(n.length!==10)throw new Error('Enter a valid 10-digit mobile number.');const auth=window.cleannoraFirebaseAuth;if(!auth)throw new Error('Login service is not ready.');if(!window.pwVerifier)window.pwVerifier=new RecaptchaVerifier(auth,'pwRecaptcha',{size:'normal'});confirmation=await signInWithPhoneNumber(auth,'+91'+n,window.pwVerifier);document.getElementById('pwOtpBox').style.display='block';msg.textContent='OTP sent.';}catch(e){msg.textContent=e.message||'Unable to send OTP.';}});
document.getElementById('pwVerifyOtp')?.addEventListener('click',async()=>{try{if(!confirmation)throw new Error('Send OTP first.');await confirmation.confirm(document.getElementById('pwOtp').value.trim());const n=document.getElementById('pwPhone').value.replace(/\D/g,'');document.getElementById('pwVerifiedPhone').value=n;document.getElementById('partnerLogin').style.display='none';document.getElementById('partnerForm').style.display='block';}catch(e){msg.textContent='Invalid OTP. Please try again.';}});
</script><?php include 'includes/footer.php';?>