<?php
$sector=strtoupper(preg_replace('/[^0-9A-Z]/i','',$_GET['sector']??''));
$allowed=['46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','70','71','72','73','74','75','76','77','78','79','93','93A','93B','94','96','97','98','99','100','101','102','104','105','107','108'];
if(!in_array($sector,$allowed,true)){http_response_code(404);$pageTitle='Service Area Not Found | CleanNora';$pageDescription='The requested CleanNora service area page is not available.';include 'includes/header.php';echo '<main class="container py-5"><h1>Service area not found</h1><p><a href="/home-services/noida">View Noida service areas</a></p></main>';include 'includes/footer.php';exit;}
$pageTitle="Home Services in Noida Sector $sector Near Me | CleanNora";
$pageDescription="Book CleanNora home services in Noida Sector $sector: maid, cook, beautician at home, home cleaning, bathroom and kitchen cleaning, AC service, electrician and plumber. Check availability near you.";
include 'includes/header.php';
$services=[['Instant Maid','/instant-maid.php'],['Instant Cook','/instant-cook.php'],['Beautician at Home','/beautician-at-home.php'],['Home Cleaning','/home-cleaning.php'],['Deep Cleaning','/deep-cleaning.php'],['Bathroom Cleaning','/bathroom-cleaning.php'],['Kitchen Cleaning','/kitchen-cleaning.php'],['Sofa Cleaning','/sofa-cleaning.php'],['AC Service & Repair','/ac-service-repair.php'],['Electrician','/electrician.php'],['Plumber','/plumber.php']];
?>
<style>.ls{max-width:1120px;margin:auto;padding:55px 20px}.ls h1{color:#063a29;font-weight:850}.ls-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:28px 0}.ls-card{border:1px solid #dfe8e3;border-radius:17px;padding:20px;text-decoration:none;color:#063a29}.ls-box{background:#f6f9f7;border-radius:18px;padding:24px;margin-top:25px}@media(max-width:700px){.ls-grid{grid-template-columns:1fr}}</style>
<main class="ls"><p><a href="/service-areas.php">Service Areas</a> › <a href="/home-services/noida">Noida</a> › Sector <?=htmlspecialchars($sector)?></p><h1>Home Services in Noida Sector <?=htmlspecialchars($sector)?> Near You</h1><p>Looking for home services near you in Noida Sector <?=htmlspecialchars($sector)?>? Check CleanNora booking options for household help, salon, cleaning and repair services. Exact serviceability, slot and Instant Priority availability are confirmed using your service address.</p><div class="ls-grid"><?php foreach($services as $s):?><a class="ls-card" href="<?=htmlspecialchars($s[1])?>"><h2><?=htmlspecialchars($s[0])?></h2><p><?=htmlspecialchars($s[0])?> in Noida Sector <?=htmlspecialchars($sector)?> — view details and booking options.</p></a><?php endforeach;?></div><section class="ls-box"><h2>Book CleanNora in Sector <?=htmlspecialchars($sector)?></h2><p>Choose a service, enter your exact address and select an available slot. For assistance call <a href="tel:+919205080012">+91 9205080012</a>.</p><h2>FAQs</h2><h3>Which services are available in Sector <?=htmlspecialchars($sector)?>?</h3><p>Availability varies by service and professional coverage. The booking flow confirms the current options for your address.</p><h3>Can I get an instant service?</h3><p>Eligible services may offer Instant Priority when a suitable professional is available nearby; otherwise regular slots remain available.</p></section></main><?php include 'includes/footer.php';?>