<?php
$pageTitle = 'Home Services Near Me in Noida, Greater Noida, Gaur City & Indirapuram | CleanNora';
$pageDescription = 'Book CleanNora maid, cook, beautician, plumber, electrician, house cleaning, toilet cleaning and car cleaning across Noida sectors, Greater Noida, Gaur City and Indirapuram.';
include 'includes/header.php';
$noida = array_merge(range(1, 168));
$greater = ['Alpha I','Alpha II','Beta I','Beta II','Gamma I','Gamma II','Delta I','Delta II','Omicron I','Omicron II','Omicron III','Zeta I','Eta I','Chi I','Phi I','Omega I','Sigma I','Mu I','Xu I','Pi I','Knowledge Park I','Knowledge Park II','Knowledge Park III','Knowledge Park IV','Knowledge Park V','Pari Chowk','Surajpur','Kasna','Techzone 1','Techzone 2','Ecotech I','Ecotech II','Ecotech III','Ecotech IV','Ecotech VI','Ecotech VII','Ecotech VIII','Ecotech IX','Ecotech X','Ecotech XI','Ecotech XII'];
$gaur = ['Gaur City 1','Gaur City 2','Gaur Saundaryam','Gaur Chowk','Greater Noida West','Noida Extension'];
$indirapuram = ['Ahinsa Khand 1','Ahinsa Khand 2','Abhay Khand 1','Abhay Khand 2','Niti Khand 1','Niti Khand 2','Niti Khand 3','Shakti Khand 1','Shakti Khand 2','Shakti Khand 3','Shakti Khand 4','Vaibhav Khand','Nyay Khand 1','Nyay Khand 2','Gyan Khand 1','Gyan Khand 2','Gyan Khand 3','Gyan Khand 4','Shipra Suncity'];
?>
<style>.area-hero{background:#063a29;color:#fff;padding:64px 0}.area-wrap{max-width:1180px;margin:auto;padding:0 20px}.area-hero h1{font-size:clamp(34px,5vw,62px);font-weight:800}.area-hero span{color:#f4bf19}.area-sec{padding:52px 0}.area-grid{display:flex;flex-wrap:wrap;gap:9px}.area-pill{border:1px solid #dbe6e1;background:#fff;border-radius:999px;padding:9px 13px;font-size:14px}.area-card{background:#f7faf8;border:1px solid #e0e9e5;border-radius:20px;padding:26px;margin-bottom:22px}.area-services{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.area-services a{padding:16px;background:#063a29;color:#fff;border-radius:14px;text-decoration:none;font-weight:700}@media(max-width:800px){.area-services{grid-template-columns:1fr 1fr}}@media(max-width:480px){.area-services{grid-template-columns:1fr}}</style>
<main><section class="area-hero"><div class="area-wrap"><h1>Home Services <span>Near You</span></h1><p>CleanNora service-area directory for Noida, Greater Noida, Gaur City and Indirapuram. Availability depends on the selected service, slot and professional coverage.</p></div></section>
<section class="area-sec"><div class="area-wrap"><h2>Services available by area</h2><div class="area-services"><a href="instant-maid.php">Instant Maid</a><a href="instant-cook.php">Instant Cook</a><a href="beautician-at-home.php">Beautician at Home</a><a href="instant-plumber.php">Instant Plumber</a><a href="services.php">Electrician</a><a href="home-cleaning.php">House Cleaning</a><a href="toilet-cleaning.php">Toilet Cleaning</a><a href="car-cleaning.php">Car Cleaning</a></div></div></section>
<section class="area-sec"><div class="area-wrap">
<div class="area-card"><h2>Noida — Sector-wise Home Services</h2><p>Search CleanNora home services across Noida sectors. Actual booking availability is confirmed during booking.</p><div class="area-grid"><?php foreach($noida as $a): ?><span class="area-pill">Noida Sector <?= $a ?></span><?php endforeach; ?><span class="area-pill">Baraula</span><span class="area-pill">Hoshiarpur</span><span class="area-pill">Mamura</span><span class="area-pill">Sarfabad</span><span class="area-pill">Hajipur</span><span class="area-pill">Gejha</span></div></div>
<div class="area-card"><h2>Greater Noida</h2><div class="area-grid"><?php foreach($greater as $a): ?><span class="area-pill"><?= htmlspecialchars($a) ?></span><?php endforeach; ?></div></div>
<div class="area-card"><h2>Gaur City & Greater Noida West</h2><div class="area-grid"><?php foreach($gaur as $a): ?><span class="area-pill"><?= htmlspecialchars($a) ?></span><?php endforeach; ?></div></div>
<div class="area-card"><h2>Indirapuram</h2><div class="area-grid"><?php foreach($indirapuram as $a): ?><span class="area-pill"><?= htmlspecialchars($a) ?></span><?php endforeach; ?></div></div>
</div></section></main>
<?php include 'includes/footer.php'; ?>
