<?php
$pageTitle='Home Services Near Me | Noida, Greater Noida, Indirapuram, Ghaziabad & Gaur City | CleanNora';
$pageDescription='Find CleanNora home services near you across Noida, Greater Noida, Greater Noida West, Gaur City, Indirapuram and Ghaziabad. Book maid, cook, salon, cleaning, AC, electrician and plumber services.';
include 'includes/header.php';
$areas=[
 ['Noida','noida','Sectors 46–61, 70–79, 93–108 and nearby neighbourhoods','201301 / 201303 / 201304 / 201305 / 201307 / 201309 / 201313'],
 ['Greater Noida','greater-noida','Alpha, Beta, Gamma, Delta, Pari Chowk, Knowledge Park, Surajpur and nearby areas','201306 / 201310 / 201311 / 201312'],
 ['Greater Noida West & Gaur City','gaur-city','Gaur City 1, Gaur City 2, Gaur Chowk, Noida Extension and nearby societies','Check exact address at booking'],
 ['Indirapuram','indirapuram','Ahinsa Khand, Niti Khand, Shakti Khand, Vaibhav Khand, Nyay Khand, Gyan Khand and Shipra Suncity','201014 and nearby postal zones'],
 ['Ghaziabad','ghaziabad','Vasundhara, Crossing Republik, Govindpuram and supported nearby neighbourhoods','201012 / 201013 / 201016 and nearby postal zones']
];
$services=[['Instant Maid','booking-service.php?service=Instant%20Maid'],['Instant Cook','booking-service.php?service=Cook'],['Home Salon & Beautician','booking-service.php?service=Salon%20Services'],['Home Cleaning','home-cleaning.php'],['Bathroom Cleaning','bathroom-cleaning.php'],['Kitchen Cleaning','kitchen-cleaning.php'],['Sofa Cleaning','sofa-cleaning.php'],['AC Service & Repair','booking-service.php?service=AC%20Service%20%26%20Repair'],['Electrician','booking-service.php?service=Electrician'],['Plumber','booking-service.php?service=Plumber']];
?>
<style>.area-hero{background:#063a29;color:#fff;padding:64px 0}.area-wrap{max-width:1180px;margin:auto;padding:0 20px}.area-hero h1{font-size:clamp(34px,5vw,58px);font-weight:800}.area-hero span{color:#f4bf19}.area-sec{padding:48px 0}.area-cards{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.area-card{background:#f7faf8;border:1px solid #e0e9e5;border-radius:20px;padding:26px}.area-card a{color:#063a29;font-weight:800}.area-services{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.area-services a{padding:15px;background:#063a29;color:#fff;border-radius:14px;text-decoration:none;font-weight:700}@media(max-width:800px){.area-cards,.area-services{grid-template-columns:1fr 1fr}}@media(max-width:480px){.area-cards,.area-services{grid-template-columns:1fr}}</style>
<main>
<section class="area-hero"><div class="area-wrap"><h1>Home Services <span>Near Me</span> Across Noida & Ghaziabad Region</h1><p>Find CleanNora maid, cook, beautician at home, home salon, cleaning, AC service, electrician and plumber services by locality. Booking availability is confirmed for your exact address and selected slot.</p></div></section>
<section class="area-sec"><div class="area-wrap"><h2>Popular Home Services Near You</h2><div class="area-services"><?php foreach($services as $s): ?><a href="<?= htmlspecialchars($s[1]) ?>"><?= htmlspecialchars($s[0]) ?></a><?php endforeach; ?></div></div></section>
<section class="area-sec"><div class="area-wrap"><h2>Choose Your Service Area</h2><div class="area-cards"><?php foreach($areas as $a): ?><article class="area-card"><h3><a href="/home-services/<?= $a[1] ?>"><?= htmlspecialchars($a[0]) ?> Home Services</a></h3><p><?= htmlspecialchars($a[2]) ?></p><p><strong>Postal coverage:</strong> <?= htmlspecialchars($a[3]) ?></p><a href="/home-services/<?= $a[1] ?>">Explore <?= htmlspecialchars($a[0]) ?> →</a></article><?php endforeach; ?></div></div></section>
</main><?php include 'includes/footer.php'; ?>